// Generated by generate_flux_source.py using the pinned NRPy 2 checkout.
#include "ghl_flux_source.h"

ghl_error_codes_t ghl_calculate_HLLE_fluxes_dirn2_tabulated_checked(ghl_primitive_quantities *restrict prims_r, ghl_primitive_quantities *restrict prims_l, const ghl_eos_parameters *restrict eos, const ghl_metric_quantities *restrict metric_face, const double cmin_dirn2, const double cmax_dirn2, ghl_conservative_quantities *restrict cons) {
  // Combine the left and right Valencia states with the HLLE flux.
  // Validate HLLE wave speeds before calling the EOS or writing fluxes.
  const double wavespeed_scale = fmax(1.0, fmax(fabs(cmin_dirn2), fabs(cmax_dirn2)));
  if(!isfinite(cmin_dirn2) || !isfinite(cmax_dirn2)
     || cmin_dirn2 < -DBL_EPSILON * wavespeed_scale
     || cmax_dirn2 < -DBL_EPSILON * wavespeed_scale) return ghl_error_invalid_hlle_wavespeeds;
  const double cmin_floored = fmax(cmin_dirn2, 0.0);
  const double cmax_floored = fmax(cmax_dirn2, 0.0);
  if(cmin_floored > DBL_MAX - cmax_floored
     || (cmin_floored > 1.0 && cmax_floored > DBL_MAX / cmin_floored))
    return ghl_error_invalid_hlle_wavespeeds;
  const double wavespeed_sum = cmin_floored + cmax_floored;
  if(wavespeed_sum <= 0.0 || wavespeed_sum < 1.0 / DBL_MAX)
    return ghl_error_invalid_hlle_wavespeeds;
  const double cmin_weight = cmin_floored / wavespeed_sum;
  const double cmax_weight = cmax_floored / wavespeed_sum;
  const double dissipation_speed = cmin_floored * cmax_floored / wavespeed_sum;
  // The EOS may update both face states before the NRPy equations read them.
  double h_r, h_l, cs2_r, cs2_l;
  ghl_error_codes_t error = ghl_compute_h_and_cs2(eos, prims_r, &h_r, &cs2_r);
  if(error != ghl_success) return error;
  error = ghl_compute_h_and_cs2(eos, prims_l, &h_l, &cs2_l);
  if(error != ghl_success) return error;
  const double u4rU0 = prims_r->u0;
  const double u4rU1 = prims_r->vU[0]*u4rU0;
  const double u4rU2 = prims_r->vU[1]*u4rU0;
  const double u4rU3 = prims_r->vU[2]*u4rU0;
  const double BrU0 = prims_r->BU[0];
  const double BrU1 = prims_r->BU[1];
  const double BrU2 = prims_r->BU[2];
  const double P_r = prims_r->press;
  const double rhob_r = prims_r->rho;
  const double u4lU0 = prims_l->u0;
  const double u4lU1 = prims_l->vU[0]*u4lU0;
  const double u4lU2 = prims_l->vU[1]*u4lU0;
  const double u4lU3 = prims_l->vU[2]*u4lU0;
  const double BlU0 = prims_l->BU[0];
  const double BlU1 = prims_l->BU[1];
  const double BlU2 = prims_l->BU[2];
  const double P_l = prims_l->press;
  const double rhob_l = prims_l->rho;
  const double alpha_face = metric_face->lapse;
  const double beta_faceU0 = metric_face->betaU[0];
  const double beta_faceU1 = metric_face->betaU[1];
  const double beta_faceU2 = metric_face->betaU[2];
  const double gamma_faceDD00 = metric_face->gammaDD[0][0];
  const double gamma_faceDD01 = metric_face->gammaDD[0][1];
  const double gamma_faceDD02 = metric_face->gammaDD[0][2];
  const double gamma_faceDD11 = metric_face->gammaDD[1][1];
  const double gamma_faceDD12 = metric_face->gammaDD[1][2];
  const double gamma_faceDD22 = metric_face->gammaDD[2][2];
  const double Y_e_r = prims_r->Y_e;
  const double Y_e_l = prims_l->Y_e;
  static const double _Integer_2 = 2;
  static const double _Rational_1_2 = 1.0/2.0;
  const double tmp0 = beta_faceU0*gamma_faceDD00 + beta_faceU1*gamma_faceDD01 + beta_faceU2*gamma_faceDD02;
  const double tmp1 = ((alpha_face)*(alpha_face));
  const double tmp5 = beta_faceU0*gamma_faceDD01 + beta_faceU1*gamma_faceDD11 + beta_faceU2*gamma_faceDD12;
  const double tmp6 = beta_faceU0*gamma_faceDD02 + beta_faceU1*gamma_faceDD12 + beta_faceU2*gamma_faceDD22;
  const double tmp13 = ((u4lU0)*(u4lU0));
  const double tmp42 = gamma_faceDD01*gamma_faceDD12 - gamma_faceDD02*gamma_faceDD11;
  const double tmp48 = -gamma_faceDD00*gamma_faceDD12 + gamma_faceDD01*gamma_faceDD02;
  const double tmp64 = ((u4rU0)*(u4rU0));
  const double tmp2 = (1.0/(tmp1));
  const double tmp3 = h_l*rhob_l*tmp1;
  const double tmp7 = BlU0*gamma_faceDD00*u4lU1 + BlU0*gamma_faceDD01*u4lU2 + BlU0*gamma_faceDD02*u4lU3 + BlU0*tmp0*u4lU0 + BlU1*gamma_faceDD01*u4lU1 + BlU1*gamma_faceDD11*u4lU2 + BlU1*gamma_faceDD12*u4lU3 + BlU1*tmp5*u4lU0 + BlU2*gamma_faceDD02*u4lU1 + BlU2*gamma_faceDD12*u4lU2 + BlU2*gamma_faceDD22*u4lU3 + BlU2*tmp6*u4lU0;
  const double tmp22 = beta_faceU0*tmp0 + beta_faceU1*tmp5 + beta_faceU2*tmp6 - tmp1;
  const double tmp32 = _Integer_2*gamma_faceDD01*gamma_faceDD02*gamma_faceDD12 + gamma_faceDD00*gamma_faceDD11*gamma_faceDD22 - gamma_faceDD00*((gamma_faceDD12)*(gamma_faceDD12)) - ((gamma_faceDD01)*(gamma_faceDD01))*gamma_faceDD22 - ((gamma_faceDD02)*(gamma_faceDD02))*gamma_faceDD11;
  const double tmp34 = gamma_faceDD00*gamma_faceDD11 - ((gamma_faceDD01)*(gamma_faceDD01));
  const double tmp56 = h_r*rhob_r*tmp1;
  const double tmp58 = BrU0*gamma_faceDD00*u4rU1 + BrU0*gamma_faceDD01*u4rU2 + BrU0*gamma_faceDD02*u4rU3 + BrU0*tmp0*u4rU0 + BrU1*gamma_faceDD01*u4rU1 + BrU1*gamma_faceDD11*u4rU2 + BrU1*gamma_faceDD12*u4rU3 + BrU1*tmp5*u4rU0 + BrU2*gamma_faceDD02*u4rU1 + BrU2*gamma_faceDD12*u4rU2 + BrU2*gamma_faceDD22*u4rU3 + BrU2*tmp6*u4rU0;
  const double tmp4 = tmp3*u4lU0;
  const double tmp8 = BlU2 + tmp7*u4lU3;
  const double tmp9 = tmp2*tmp7/u4lU0;
  const double tmp11 = BlU0 + tmp7*u4lU1;
  const double tmp12 = BlU1 + tmp7*u4lU2;
  const double tmp14 = tmp2/tmp13;
  const double tmp23 = tmp2*((tmp7)*(tmp7));
  const double tmp36 = -((beta_faceU2)*(beta_faceU2))*tmp32 + tmp1*tmp34;
  const double tmp37 = (1.0/(tmp32));
  const double tmp44 = -beta_faceU0*beta_faceU2*tmp32 + tmp1*tmp42;
  const double tmp50 = -beta_faceU1*beta_faceU2*tmp32 + tmp1*tmp48;
  const double tmp53 = sqrt(tmp32);
  const double tmp57 = tmp56*u4rU0;
  const double tmp59 = BrU2 + tmp58*u4rU3;
  const double tmp60 = tmp2*tmp58/u4rU0;
  const double tmp62 = BrU0 + tmp58*u4rU1;
  const double tmp63 = BrU1 + tmp58*u4rU2;
  const double tmp65 = tmp2/tmp64;
  const double tmp73 = tmp2*((tmp58)*(tmp58));
  const double tmp21 = tmp14*((tmp8)*(tmp8));
  const double tmp38 = tmp2*tmp37;
  const double tmp39 = -((beta_faceU2)*(beta_faceU2))*tmp2 + tmp34*tmp37;
  const double tmp41 = tmp3*tmp32*u4lU3;
  const double tmp46 = -beta_faceU0*beta_faceU2*tmp2 + tmp37*tmp42;
  const double tmp51 = -beta_faceU1*beta_faceU2*tmp2 + tmp37*tmp48;
  const double tmp54 = alpha_face*tmp53;
  const double tmp72 = ((tmp59)*(tmp59))*tmp65;
  const double tmp83 = tmp32*tmp56*u4rU3;
  const double tmp100 = tmp1*tmp53;
  const double tmp16 = tmp11*tmp14*tmp8;
  const double tmp17 = tmp12*tmp14*tmp8;
  const double tmp24 = gamma_faceDD00*((tmp11)*(tmp11))*tmp14 + gamma_faceDD11*((tmp12)*(tmp12))*tmp14 + gamma_faceDD22*tmp21 + tmp22*tmp23;
  const double tmp55 = cmax_weight*tmp54;
  const double tmp67 = tmp59*tmp62*tmp65;
  const double tmp68 = tmp59*tmp63*tmp65;
  const double tmp74 = gamma_faceDD00*((tmp62)*(tmp62))*tmp65 + gamma_faceDD11*((tmp63)*(tmp63))*tmp65 + gamma_faceDD22*tmp72 + tmp22*tmp73;
  const double tmp87 = cmin_weight*tmp54;
  const double tmp20 = gamma_faceDD01*tmp11*tmp12*tmp14 + gamma_faceDD02*tmp16 + gamma_faceDD12*tmp17 + tmp0*tmp11*tmp9 + tmp12*tmp5*tmp9 + tmp6*tmp8*tmp9;
  const double tmp71 = gamma_faceDD01*tmp62*tmp63*tmp65 + gamma_faceDD02*tmp67 + gamma_faceDD12*tmp68 + tmp0*tmp60*tmp62 + tmp5*tmp60*tmp63 + tmp59*tmp6*tmp60;
  const double tmp94 = rhob_l*tmp55*u4lU3;
  const double tmp95 = rhob_r*tmp87*u4rU3;
  const double tmp97 = rhob_l*tmp54*u4lU0;
  const double tmp99 = rhob_r*tmp54*u4rU0;
  const double tmp25 = _Integer_2*tmp20 + tmp24;
  const double tmp27 = _Rational_1_2*tmp24 + tmp20;
  const double tmp75 = _Integer_2*tmp71 + tmp74;
  const double tmp77 = _Rational_1_2*tmp74 + tmp71;
  const double tmp26 = tmp25*u4lU0;
  const double tmp28 = tmp2*tmp27;
  const double tmp40 = -tmp21 + tmp25*((u4lU3)*(u4lU3)) + tmp27*tmp39 + tmp38*(P_l*tmp36 + tmp3*tmp32*((u4lU3)*(u4lU3)));
  const double tmp76 = tmp75*u4rU0;
  const double tmp78 = tmp2*tmp77;
  const double tmp82 = tmp38*(P_r*tmp36 + tmp32*tmp56*((u4rU3)*(u4rU3))) + tmp39*tmp77 - tmp72 + tmp75*((u4rU3)*(u4rU3));
  const double tmp29 = beta_faceU2*tmp28 + tmp2*(P_l*beta_faceU2 + tmp4*u4lU3) + tmp26*u4lU3 - tmp8*tmp9;
  const double tmp47 = -tmp16 + tmp25*u4lU1*u4lU3 + tmp27*tmp46 + tmp38*(P_l*tmp44 + tmp41*u4lU1);
  const double tmp52 = -tmp17 + tmp25*u4lU2*u4lU3 + tmp27*tmp51 + tmp38*(P_l*tmp50 + tmp41*u4lU2);
  const double tmp79 = beta_faceU2*tmp78 + tmp2*(P_r*beta_faceU2 + tmp57*u4rU3) - tmp59*tmp60 + tmp76*u4rU3;
  const double tmp85 = tmp38*(P_r*tmp44 + tmp83*u4rU1) + tmp46*tmp77 - tmp67 + tmp75*u4rU1*u4rU3;
  const double tmp86 = tmp38*(P_r*tmp50 + tmp83*u4rU2) + tmp51*tmp77 - tmp68 + tmp75*u4rU2*u4rU3;
  const double tmp88 = tmp13*tmp25 + tmp2*(-P_l + h_l*rhob_l*tmp1*tmp13) - tmp23 - tmp28;
  const double tmp89 = beta_faceU0*tmp28 - tmp11*tmp9 + tmp2*(P_l*beta_faceU0 + tmp4*u4lU1) + tmp26*u4lU1;
  const double tmp90 = beta_faceU1*tmp28 - tmp12*tmp9 + tmp2*(P_l*beta_faceU1 + tmp4*u4lU2) + tmp26*u4lU2;
  const double tmp91 = tmp2*(-P_r + h_r*rhob_r*tmp1*tmp64) + tmp64*tmp75 - tmp73 - tmp78;
  const double tmp92 = beta_faceU0*tmp78 + tmp2*(P_r*beta_faceU0 + tmp57*u4rU1) - tmp60*tmp62 + tmp76*u4rU1;
  const double tmp93 = beta_faceU1*tmp78 + tmp2*(P_r*beta_faceU1 + tmp57*u4rU2) - tmp60*tmp63 + tmp76*u4rU2;
  cons->SD[0] = -dissipation_speed*(alpha_face*tmp53*(gamma_faceDD00*tmp92 + gamma_faceDD01*tmp93 + gamma_faceDD02*tmp79 + tmp0*tmp91) - tmp54*(gamma_faceDD00*tmp89 + gamma_faceDD01*tmp90 + gamma_faceDD02*tmp29 + tmp0*tmp88)) + tmp55*(gamma_faceDD00*tmp47 + gamma_faceDD01*tmp52 + gamma_faceDD02*tmp40 + tmp0*tmp29) + tmp87*(gamma_faceDD00*tmp85 + gamma_faceDD01*tmp86 + gamma_faceDD02*tmp82 + tmp0*tmp79);
  cons->SD[1] = -dissipation_speed*(alpha_face*tmp53*(gamma_faceDD01*tmp92 + gamma_faceDD11*tmp93 + gamma_faceDD12*tmp79 + tmp5*tmp91) - tmp54*(gamma_faceDD01*tmp89 + gamma_faceDD11*tmp90 + gamma_faceDD12*tmp29 + tmp5*tmp88)) + tmp55*(gamma_faceDD01*tmp47 + gamma_faceDD11*tmp52 + gamma_faceDD12*tmp40 + tmp29*tmp5) + tmp87*(gamma_faceDD01*tmp85 + gamma_faceDD11*tmp86 + gamma_faceDD12*tmp82 + tmp5*tmp79);
  cons->SD[2] = -dissipation_speed*(alpha_face*tmp53*(gamma_faceDD02*tmp92 + gamma_faceDD12*tmp93 + gamma_faceDD22*tmp79 + tmp6*tmp91) - tmp54*(gamma_faceDD02*tmp89 + gamma_faceDD12*tmp90 + gamma_faceDD22*tmp29 + tmp6*tmp88)) + tmp55*(gamma_faceDD02*tmp47 + gamma_faceDD12*tmp52 + gamma_faceDD22*tmp40 + tmp29*tmp6) + tmp87*(gamma_faceDD02*tmp85 + gamma_faceDD12*tmp86 + gamma_faceDD22*tmp82 + tmp6*tmp79);
  cons->rho = -dissipation_speed*(-tmp97 + tmp99) + tmp94 + tmp95;
  cons->tau = cmax_weight*(-rhob_l*tmp54*u4lU3 + tmp100*tmp29) + cmin_weight*(-rhob_r*tmp54*u4rU3 + tmp100*tmp79) - dissipation_speed*(tmp1*tmp53*tmp91 - tmp100*tmp88 + tmp97 - tmp99);
  cons->Y_e = Y_e_l*tmp94 + Y_e_r*tmp95 - dissipation_speed*(-Y_e_l*tmp97 + Y_e_r*alpha_face*rhob_r*tmp53*u4rU0);
  return ghl_success;
}

void ghl_calculate_HLLE_fluxes_dirn2_tabulated(ghl_primitive_quantities *restrict prims_r, ghl_primitive_quantities *restrict prims_l, const ghl_eos_parameters *restrict eos, const ghl_metric_quantities *restrict metric_face, const double cmin_dirn2, const double cmax_dirn2, ghl_conservative_quantities *restrict cons) {
  ghl_abort_if_error(ghl_calculate_HLLE_fluxes_dirn2_tabulated_checked(prims_r, prims_l, eos, metric_face, cmin_dirn2, cmax_dirn2, cons));
}
