name: compile_GRHayL
description: 'Compile GRHayL using selected compiler'
inputs:
  OS:
    description: OS for test
    required: true
    default: 'Ubuntu'
  compiler:
    description: compiler for test
    required: true
    default: 'gcc'

runs:
  using: "composite"
  steps:
    - if: inputs.OS == 'Ubuntu' && inputs.compiler == 'gcc'
      run: CC=gcc ./configure --prefix=`pwd` --compile-silent
      shell: bash

    - if: inputs.OS == 'Ubuntu' && inputs.compiler == 'clang'
      run: CC=clang-14 ./configure --prefix=`pwd` --compile-silent
      shell: bash

    - if: inputs.OS == 'Ubuntu' && inputs.compiler == 'intel'
      run: |
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV
        CC=icx ./configure --prefix=`pwd` --compile-silent
      shell: bash

    - if: inputs.OS == 'Mac' && inputs.compiler == 'gcc'
      run: CC=gcc-12 ./configure --prefix=`pwd` --compile-silent
      shell: bash

    - if: inputs.OS == 'Mac' && inputs.compiler == 'clang'
      run: |
        export CC=`ls $(brew --prefix)/opt/llvm/bin/clang-** | egrep 'clang-[0-9]{2}$'`
        export LDFLAGS="-L$(brew --prefix)/opt/llvm/lib"
        export CPPFLAGS="-I$(brew --prefix)/opt/llvm/include"
        ./configure --prefix=`pwd` --compile-silent
      shell: bash

    - run: |
        make
        make install
      shell: bash
