#!/bin/sh

if [ $# -ne 3 ]; then
    printf "Correct usage: $0 <awk flavor> <make.code.defn file path> <what to extract>\n"
    exit 1
fi

case $3 in
    sources) out=$($1 -f scripts/match_all.awk \
                        -v re_start="^ *SRCS" \
                        -v re_end="^ *$" \
                        -v re_in="[a-zA-Z0-9_.]*\\\\.c" \
                        -v set_path=1 \
                        $2);;

    subdirs) out=$($1 -f scripts/match_all.awk \
                        -v re_start="^ *SUBDIRS" \
                        -v re_end="^ *$" \
                        -v re_in="[a-zA-z0-9_./]*" \
                        $2 | $1 '{ sub(/SUBDIRS */, "", $0); gsub(/[ \t]*\\/, " ", $0); print }');;

    headers) out=$($1 -f scripts/match_all.awk \
                      -v re_start="^#! *INCS" \
                      -v re_end="^ *$" \
                      -v re_in="[a-zA-Z0-9_.]*\\\\.h" \
                      -v set_path=1 \
                      $2);;

    install_headers) out=$($1 -f scripts/match_all.awk \
                                -v re_start="^#! *install_headers" \
                                -v re_end="^ *$" \
                                -v re_in="[a-zA-Z0-9_.]*\\\\.h" \
                                -v set_path=1 \
                                $2);;
esac

echo $out
