// Generated by generate_flux_source.py using the pinned NRPy 2 checkout.
#include "ghl_flux_source.h"

ghl_error_codes_t ghl_calculate_characteristic_speed_dirn1_checked(ghl_primitive_quantities *restrict prims_r, ghl_primitive_quantities *restrict prims_l, const ghl_eos_parameters *restrict eos, const ghl_metric_quantities *restrict metric_face, double *cmin_dirn1, double *cmax_dirn1) {
  // Solve the GRMHD fast-wave characteristic quadratic on this face.
  // The EOS may update both face states before the NRPy equations read them.
  double h_r, h_l, cs2_r, cs2_l;
  ghl_error_codes_t error = ghl_compute_h_and_cs2(eos, prims_r, &h_r, &cs2_r);
  if(error != ghl_success) {
    return error;
  }
  error = ghl_compute_h_and_cs2(eos, prims_l, &h_l, &cs2_l);
  if(error != ghl_success) {
    return error;
  }
  const double u4rU0 = prims_r->u0;
  const double u4rU1 = prims_r->vU[0]*u4rU0;
  const double u4rU2 = prims_r->vU[1]*u4rU0;
  const double u4rU3 = prims_r->vU[2]*u4rU0;
  const double BrU0 = prims_r->BU[0];
  const double BrU1 = prims_r->BU[1];
  const double BrU2 = prims_r->BU[2];
  const double rhob_r = prims_r->rho;
  const double u4lU0 = prims_l->u0;
  const double u4lU1 = prims_l->vU[0]*u4lU0;
  const double u4lU2 = prims_l->vU[1]*u4lU0;
  const double u4lU3 = prims_l->vU[2]*u4lU0;
  const double BlU0 = prims_l->BU[0];
  const double BlU1 = prims_l->BU[1];
  const double BlU2 = prims_l->BU[2];
  const double rhob_l = prims_l->rho;
  const double alpha_face = metric_face->lapse;
  const double beta_faceU0 = metric_face->betaU[0];
  const double beta_faceU1 = metric_face->betaU[1];
  const double beta_faceU2 = metric_face->betaU[2];
  const double gamma_faceDD00 = metric_face->gammaDD[0][0];
  const double gamma_faceDD01 = metric_face->gammaDD[0][1];
  const double gamma_faceDD02 = metric_face->gammaDD[0][2];
  const double gamma_faceDD11 = metric_face->gammaDD[1][1];
  const double gamma_faceDD12 = metric_face->gammaDD[1][2];
  const double gamma_faceDD22 = metric_face->gammaDD[2][2];
  // Magnetic fast-wave speed squared for right and left states.
  double v02_r, v02_l;
  {
  static const double _Integer_1 = 1;
  static const double _Integer_2 = 2;
  const double tmp0 = beta_faceU0*gamma_faceDD00 + beta_faceU1*gamma_faceDD01 + beta_faceU2*gamma_faceDD02;
  const double tmp1 = beta_faceU0*gamma_faceDD01 + beta_faceU1*gamma_faceDD11 + beta_faceU2*gamma_faceDD12;
  const double tmp2 = beta_faceU0*gamma_faceDD02 + beta_faceU1*gamma_faceDD12 + beta_faceU2*gamma_faceDD22;
  const double tmp3 = BrU0*gamma_faceDD00*u4rU1 + BrU0*gamma_faceDD01*u4rU2 + BrU0*gamma_faceDD02*u4rU3 + BrU0*tmp0*u4rU0 + BrU1*gamma_faceDD01*u4rU1 + BrU1*gamma_faceDD11*u4rU2 + BrU1*gamma_faceDD12*u4rU3 + BrU1*tmp1*u4rU0 + BrU2*gamma_faceDD02*u4rU1 + BrU2*gamma_faceDD12*u4rU2 + BrU2*gamma_faceDD22*u4rU3 + BrU2*tmp2*u4rU0;
  const double tmp6 = (1.0/((alpha_face)*(alpha_face)));
  const double tmp17 = BlU0*gamma_faceDD00*u4lU1 + BlU0*gamma_faceDD01*u4lU2 + BlU0*gamma_faceDD02*u4lU3 + BlU0*tmp0*u4lU0 + BlU1*gamma_faceDD01*u4lU1 + BlU1*gamma_faceDD11*u4lU2 + BlU1*gamma_faceDD12*u4lU3 + BlU1*tmp1*u4lU0 + BlU2*gamma_faceDD02*u4lU1 + BlU2*gamma_faceDD12*u4lU2 + BlU2*gamma_faceDD22*u4lU3 + BlU2*tmp2*u4lU0;
  const double tmp4 = BrU0 + tmp3*u4rU1;
  const double tmp7 = tmp6/((u4rU0)*(u4rU0));
  const double tmp8 = BrU1 + tmp3*u4rU2;
  const double tmp9 = BrU2 + tmp3*u4rU3;
  const double tmp10 = tmp6*(-((alpha_face)*(alpha_face)) + beta_faceU0*tmp0 + beta_faceU1*tmp1 + beta_faceU2*tmp2);
  const double tmp13 = tmp3/u4rU0;
  const double tmp18 = BlU0 + tmp17*u4lU1;
  const double tmp19 = tmp6/((u4lU0)*(u4lU0));
  const double tmp20 = BlU1 + tmp17*u4lU2;
  const double tmp21 = BlU2 + tmp17*u4lU3;
  const double tmp23 = tmp17/u4lU0;
  const double tmp15 = _Integer_2*(gamma_faceDD01*tmp4*tmp7*tmp8 + gamma_faceDD02*tmp4*tmp7*tmp9 + gamma_faceDD12*tmp7*tmp8*tmp9 + tmp0*tmp13*tmp4*tmp6 + tmp1*tmp13*tmp6*tmp8 + tmp13*tmp2*tmp6*tmp9) + gamma_faceDD00*((tmp4)*(tmp4))*tmp7 + gamma_faceDD11*tmp7*((tmp8)*(tmp8)) + gamma_faceDD22*tmp7*((tmp9)*(tmp9)) + tmp10*((tmp3)*(tmp3));
  const double tmp25 = _Integer_2*(gamma_faceDD01*tmp18*tmp19*tmp20 + gamma_faceDD02*tmp18*tmp19*tmp21 + gamma_faceDD12*tmp19*tmp20*tmp21 + tmp0*tmp18*tmp23*tmp6 + tmp1*tmp20*tmp23*tmp6 + tmp2*tmp21*tmp23*tmp6) + gamma_faceDD00*((tmp18)*(tmp18))*tmp19 + gamma_faceDD11*tmp19*((tmp20)*(tmp20)) + gamma_faceDD22*tmp19*((tmp21)*(tmp21)) + tmp10*((tmp17)*(tmp17));
  const double tmp16 = tmp15/(h_r*rhob_r + tmp15);
  const double tmp26 = tmp25/(h_l*rhob_l + tmp25);
  v02_r = cs2_r*(_Integer_1 - tmp16) + tmp16;
  v02_l = cs2_l*(_Integer_1 - tmp26) + tmp26;
  }
  static const double _Rational_1_2 = 1.0/2.0;
  static const double _Integer_1 = 1;
  static const double _Integer_2 = 2;
  static const double _Integer_4 = 4;
  static const double _Rational_1_4 = 1.0/4.0;
  static const double _Rational_1_8 = 1.0/8.0;
  static const double _Rational_1_16 = 1.0/16.0;
  const double tmp0 = (1.0/((alpha_face)*(alpha_face)));
  const double tmp1 = _Integer_1 - v02_l;
  const double tmp7 = _Integer_1 - v02_r;
  const double tmp2 = -beta_faceU1*tmp0*v02_l + tmp1*u4lU0*u4lU2;
  const double tmp4 = tmp0*v02_l + tmp1*((u4lU0)*(u4lU0));
  const double tmp8 = -beta_faceU1*tmp0*v02_r + tmp7*u4rU0*u4rU2;
  const double tmp10 = tmp0*v02_r + tmp7*((u4rU0)*(u4rU0));
  const double tmp19 = -((beta_faceU1)*(beta_faceU1))*tmp0 + (gamma_faceDD00*gamma_faceDD22 - ((gamma_faceDD02)*(gamma_faceDD02)))/(_Integer_2*gamma_faceDD01*gamma_faceDD02*gamma_faceDD12 + gamma_faceDD00*gamma_faceDD11*gamma_faceDD22 - gamma_faceDD00*((gamma_faceDD12)*(gamma_faceDD12)) - ((gamma_faceDD01)*(gamma_faceDD01))*gamma_faceDD22 - ((gamma_faceDD02)*(gamma_faceDD02))*gamma_faceDD11);
  const double tmp5 = (1.0/(tmp4));
  const double tmp11 = (1.0/(tmp10));
  const double tmp6 = -tmp2*tmp5;
  const double tmp12 = -tmp11*tmp8;
  const double tmp13 = tmp2*tmp5;
  const double tmp14 = tmp11*tmp8;
  const double tmp20 = ((_Integer_2)*(_Integer_2))*((tmp2)*(tmp2)) - _Integer_4*tmp4*(tmp1*((u4lU2)*(u4lU2)) - tmp19*v02_l);
  const double tmp22 = ((_Integer_2)*(_Integer_2))*((tmp8)*(tmp8)) - _Integer_4*tmp10*(-tmp19*v02_r + tmp7*((u4rU2)*(u4rU2)));
  const double tmp15 = _Rational_1_16*tmp12 - _Rational_1_16*tmp13 - _Rational_1_16*tmp14 + _Rational_1_16*tmp6;
  const double tmp21 = fabs(_Integer_2*_Rational_1_2*(tmp13 + tmp6) + tmp5*sqrt(_Rational_1_2*(tmp20 + fabs(tmp20))));
  const double tmp23 = fabs(_Integer_2*_Rational_1_2*(tmp12 + tmp14) + tmp11*sqrt(_Rational_1_2*(tmp22 + fabs(tmp22))));
  const double tmp26 = tmp12 - tmp14;
  const double tmp24 = tmp21 + tmp23;
  const double tmp27 = _Integer_2*_Rational_1_4*(tmp13 + tmp26 - tmp6);
  const double tmp28 = tmp21 - tmp23;
  const double tmp30 = _Integer_2*_Rational_1_8*(-tmp13 + tmp26 + tmp6);
  const double tmp29 = fabs(-_Rational_1_2*tmp28 + tmp27);
  const double tmp31 = fabs(_Rational_1_2*tmp28 + tmp27);
  *cmin_dirn1 = _Integer_2*tmp15 + _Rational_1_2*fabs(_Rational_1_2*tmp29 + _Rational_1_4*tmp24 + tmp30) + _Rational_1_4*tmp29 + _Rational_1_8*tmp24;
  *cmax_dirn1 = -_Integer_2*tmp15 + _Rational_1_2*fabs(-_Rational_1_2*tmp31 - _Rational_1_4*tmp24 + tmp30) + _Rational_1_4*tmp31 + _Rational_1_8*tmp24;
  return ghl_success;
}

void ghl_calculate_characteristic_speed_dirn1(ghl_primitive_quantities *restrict prims_r, ghl_primitive_quantities *restrict prims_l, const ghl_eos_parameters *restrict eos, const ghl_metric_quantities *restrict metric_face, double *cmin_dirn1, double *cmax_dirn1) {
  ghl_abort_if_error(ghl_calculate_characteristic_speed_dirn1_checked(prims_r, prims_l, eos, metric_face, cmin_dirn1, cmax_dirn1));
}
