// Generated by generate_flux_source.py using the pinned NRPy 2 checkout.
#include "ghl_flux_source.h"

ghl_error_codes_t ghl_calculate_HLLE_fluxes_dirn1_hybrid_entropy_checked(ghl_primitive_quantities *restrict prims_r, ghl_primitive_quantities *restrict prims_l, const ghl_eos_parameters *restrict eos, const ghl_metric_quantities *restrict metric_face, const double cmin_dirn1, const double cmax_dirn1, ghl_conservative_quantities *restrict cons) {
  // Combine the left and right Valencia states with the HLLE flux.
  // Validate HLLE wave speeds before calling the EOS or writing fluxes.
  const double wavespeed_scale = fmax(1.0, fmax(fabs(cmin_dirn1), fabs(cmax_dirn1)));
  if(!isfinite(cmin_dirn1) || !isfinite(cmax_dirn1)
     || cmin_dirn1 < -DBL_EPSILON * wavespeed_scale
     || cmax_dirn1 < -DBL_EPSILON * wavespeed_scale) {
    return ghl_error_invalid_hlle_wavespeeds;
  }
  const double cmin_floored = fmax(cmin_dirn1, 0.0);
  const double cmax_floored = fmax(cmax_dirn1, 0.0);
  if(cmin_floored > DBL_MAX - cmax_floored
     || (cmin_floored > 1.0 && cmax_floored > DBL_MAX / cmin_floored)) {
    return ghl_error_invalid_hlle_wavespeeds;
  }
  const double wavespeed_sum = cmin_floored + cmax_floored;
  if(wavespeed_sum <= 0.0 || wavespeed_sum < 1.0 / DBL_MAX) {
    return ghl_error_invalid_hlle_wavespeeds;
  }
  const double cmin_weight = cmin_floored / wavespeed_sum;
  const double cmax_weight = cmax_floored / wavespeed_sum;
  const double dissipation_speed = cmin_floored * cmax_floored / wavespeed_sum;
  // The EOS may update both face states before the NRPy equations read them.
  double h_r, h_l, cs2_r, cs2_l;
  ghl_error_codes_t error = ghl_compute_h_and_cs2(eos, prims_r, &h_r, &cs2_r);
  if(error != ghl_success) {
    return error;
  }
  error = ghl_compute_h_and_cs2(eos, prims_l, &h_l, &cs2_l);
  if(error != ghl_success) {
    return error;
  }
  const double u4rU0 = prims_r->u0;
  const double u4rU1 = prims_r->vU[0]*u4rU0;
  const double u4rU2 = prims_r->vU[1]*u4rU0;
  const double u4rU3 = prims_r->vU[2]*u4rU0;
  const double BrU0 = prims_r->BU[0];
  const double BrU1 = prims_r->BU[1];
  const double BrU2 = prims_r->BU[2];
  const double P_r = prims_r->press;
  const double rhob_r = prims_r->rho;
  const double u4lU0 = prims_l->u0;
  const double u4lU1 = prims_l->vU[0]*u4lU0;
  const double u4lU2 = prims_l->vU[1]*u4lU0;
  const double u4lU3 = prims_l->vU[2]*u4lU0;
  const double BlU0 = prims_l->BU[0];
  const double BlU1 = prims_l->BU[1];
  const double BlU2 = prims_l->BU[2];
  const double P_l = prims_l->press;
  const double rhob_l = prims_l->rho;
  const double alpha_face = metric_face->lapse;
  const double beta_faceU0 = metric_face->betaU[0];
  const double beta_faceU1 = metric_face->betaU[1];
  const double beta_faceU2 = metric_face->betaU[2];
  const double gamma_faceDD00 = metric_face->gammaDD[0][0];
  const double gamma_faceDD01 = metric_face->gammaDD[0][1];
  const double gamma_faceDD02 = metric_face->gammaDD[0][2];
  const double gamma_faceDD11 = metric_face->gammaDD[1][1];
  const double gamma_faceDD12 = metric_face->gammaDD[1][2];
  const double gamma_faceDD22 = metric_face->gammaDD[2][2];
  const double S_r = prims_r->entropy;
  const double S_l = prims_l->entropy;
  static const double _Integer_2 = 2;
  static const double _Rational_1_2 = 1.0/2.0;
  const double tmp0 = beta_faceU0*gamma_faceDD00 + beta_faceU1*gamma_faceDD01 + beta_faceU2*gamma_faceDD02;
  const double tmp1 = beta_faceU0*gamma_faceDD01 + beta_faceU1*gamma_faceDD11 + beta_faceU2*gamma_faceDD12;
  const double tmp2 = beta_faceU0*gamma_faceDD02 + beta_faceU1*gamma_faceDD12 + beta_faceU2*gamma_faceDD22;
  const double tmp5 = ((alpha_face)*(alpha_face));
  const double tmp3 = BlU0*(gamma_faceDD00*u4lU1 + gamma_faceDD01*u4lU2 + gamma_faceDD02*u4lU3 + tmp0*u4lU0) + BlU1*(gamma_faceDD01*u4lU1 + gamma_faceDD11*u4lU2 + gamma_faceDD12*u4lU3 + tmp1*u4lU0) + BlU2*(gamma_faceDD02*u4lU1 + gamma_faceDD12*u4lU2 + gamma_faceDD22*u4lU3 + tmp2*u4lU0);
  const double tmp6 = (1.0/(tmp5));
  const double tmp20 = beta_faceU0*tmp0 + beta_faceU1*tmp1 + beta_faceU2*tmp2 - tmp5;
  const double tmp25 = _Integer_2*gamma_faceDD01*gamma_faceDD02*gamma_faceDD12 + gamma_faceDD00*gamma_faceDD11*gamma_faceDD22 - gamma_faceDD00*((gamma_faceDD12)*(gamma_faceDD12)) - ((gamma_faceDD01)*(gamma_faceDD01))*gamma_faceDD22 - ((gamma_faceDD02)*(gamma_faceDD02))*gamma_faceDD11;
  const double tmp42 = BrU0*(gamma_faceDD00*u4rU1 + gamma_faceDD01*u4rU2 + gamma_faceDD02*u4rU3 + tmp0*u4rU0) + BrU1*(gamma_faceDD01*u4rU1 + gamma_faceDD11*u4rU2 + gamma_faceDD12*u4rU3 + tmp1*u4rU0) + BrU2*(gamma_faceDD02*u4rU1 + gamma_faceDD12*u4rU2 + gamma_faceDD22*u4rU3 + tmp2*u4rU0);
  const double tmp4 = BlU1 + tmp3*u4lU2;
  const double tmp8 = tmp6/((u4lU0)*(u4lU0));
  const double tmp10 = BlU0 + tmp3*u4lU1;
  const double tmp13 = BlU2 + tmp3*u4lU3;
  const double tmp15 = tmp3*tmp6/u4lU0;
  const double tmp21 = ((tmp3)*(tmp3))*tmp6;
  const double tmp26 = (1.0/(tmp25));
  const double tmp39 = sqrt(tmp25);
  const double tmp43 = BrU1 + tmp42*u4rU2;
  const double tmp45 = tmp6/((u4rU0)*(u4rU0));
  const double tmp47 = BrU0 + tmp42*u4rU1;
  const double tmp50 = BrU2 + tmp42*u4rU3;
  const double tmp52 = tmp42*tmp6/u4rU0;
  const double tmp57 = ((tmp42)*(tmp42))*tmp6;
  const double tmp9 = ((tmp4)*(tmp4))*tmp8;
  const double tmp27 = -((beta_faceU1)*(beta_faceU1))*tmp6 + tmp26*(gamma_faceDD00*gamma_faceDD22 - ((gamma_faceDD02)*(gamma_faceDD02)));
  const double tmp35 = -beta_faceU0*beta_faceU1*tmp6 + tmp26*(-gamma_faceDD01*gamma_faceDD22 + gamma_faceDD02*gamma_faceDD12);
  const double tmp37 = -beta_faceU1*beta_faceU2*tmp6 + tmp26*(-gamma_faceDD00*gamma_faceDD12 + gamma_faceDD01*gamma_faceDD02);
  const double tmp40 = alpha_face*tmp39;
  const double tmp46 = ((tmp43)*(tmp43))*tmp45;
  const double tmp81 = tmp39*tmp5;
  const double tmp12 = tmp10*tmp4*tmp8;
  const double tmp14 = tmp13*tmp4*tmp8;
  const double tmp22 = gamma_faceDD00*((tmp10)*(tmp10))*tmp8 + gamma_faceDD11*tmp9 + gamma_faceDD22*((tmp13)*(tmp13))*tmp8 + tmp20*tmp21;
  const double tmp41 = cmax_weight*tmp40;
  const double tmp49 = tmp43*tmp45*tmp47;
  const double tmp51 = tmp43*tmp45*tmp50;
  const double tmp58 = gamma_faceDD00*tmp45*((tmp47)*(tmp47)) + gamma_faceDD11*tmp46 + gamma_faceDD22*tmp45*((tmp50)*(tmp50)) + tmp20*tmp57;
  const double tmp68 = cmin_weight*tmp40;
  const double tmp19 = gamma_faceDD01*tmp12 + gamma_faceDD02*tmp10*tmp13*tmp8 + gamma_faceDD12*tmp14 + tmp0*tmp10*tmp15 + tmp1*tmp15*tmp4 + tmp13*tmp15*tmp2;
  const double tmp56 = gamma_faceDD01*tmp49 + gamma_faceDD02*tmp45*tmp47*tmp50 + gamma_faceDD12*tmp51 + tmp0*tmp47*tmp52 + tmp1*tmp43*tmp52 + tmp2*tmp50*tmp52;
  const double tmp78 = rhob_l*tmp40*u4lU0;
  const double tmp80 = rhob_r*tmp40*u4rU0;
  const double tmp23 = _Integer_2*tmp19 + h_l*rhob_l + tmp22;
  const double tmp28 = P_l + _Rational_1_2*tmp22 + tmp19;
  const double tmp59 = _Integer_2*tmp56 + h_r*rhob_r + tmp58;
  const double tmp60 = P_r + _Rational_1_2*tmp58 + tmp56;
  const double tmp29 = tmp23*((u4lU2)*(u4lU2)) + tmp27*tmp28 - tmp9;
  const double tmp30 = tmp28*tmp6;
  const double tmp31 = tmp23*u4lU0;
  const double tmp61 = tmp27*tmp60 - tmp46 + tmp59*((u4rU2)*(u4rU2));
  const double tmp62 = tmp6*tmp60;
  const double tmp63 = tmp59*u4rU0;
  const double tmp32 = beta_faceU1*tmp30 - tmp15*tmp4 + tmp31*u4lU2;
  const double tmp36 = -tmp12 + tmp23*u4lU1*u4lU2 + tmp28*tmp35;
  const double tmp38 = -tmp14 + tmp23*u4lU2*u4lU3 + tmp28*tmp37;
  const double tmp64 = beta_faceU1*tmp62 - tmp43*tmp52 + tmp63*u4rU2;
  const double tmp66 = tmp35*tmp60 - tmp49 + tmp59*u4rU1*u4rU2;
  const double tmp67 = tmp37*tmp60 - tmp51 + tmp59*u4rU2*u4rU3;
  const double tmp69 = -tmp21 + tmp23*((u4lU0)*(u4lU0)) - tmp30;
  const double tmp70 = beta_faceU0*tmp30 - tmp10*tmp15 + tmp31*u4lU1;
  const double tmp71 = beta_faceU2*tmp30 - tmp13*tmp15 + tmp31*u4lU3;
  const double tmp72 = -tmp57 + tmp59*((u4rU0)*(u4rU0)) - tmp62;
  const double tmp73 = beta_faceU0*tmp62 - tmp47*tmp52 + tmp63*u4rU1;
  const double tmp74 = beta_faceU2*tmp62 - tmp50*tmp52 + tmp63*u4rU3;
  cons->SD[0] = -dissipation_speed*(alpha_face*tmp39*(gamma_faceDD00*tmp73 + gamma_faceDD01*tmp64 + gamma_faceDD02*tmp74 + tmp0*tmp72) - tmp40*(gamma_faceDD00*tmp70 + gamma_faceDD01*tmp32 + gamma_faceDD02*tmp71 + tmp0*tmp69)) + tmp41*(gamma_faceDD00*tmp36 + gamma_faceDD01*tmp29 + gamma_faceDD02*tmp38 + tmp0*tmp32) + tmp68*(gamma_faceDD00*tmp66 + gamma_faceDD01*tmp61 + gamma_faceDD02*tmp67 + tmp0*tmp64);
  cons->SD[1] = -dissipation_speed*(alpha_face*tmp39*(gamma_faceDD01*tmp73 + gamma_faceDD11*tmp64 + gamma_faceDD12*tmp74 + tmp1*tmp72) - tmp40*(gamma_faceDD01*tmp70 + gamma_faceDD11*tmp32 + gamma_faceDD12*tmp71 + tmp1*tmp69)) + tmp41*(gamma_faceDD01*tmp36 + gamma_faceDD11*tmp29 + gamma_faceDD12*tmp38 + tmp1*tmp32) + tmp68*(gamma_faceDD01*tmp66 + gamma_faceDD11*tmp61 + gamma_faceDD12*tmp67 + tmp1*tmp64);
  cons->SD[2] = -dissipation_speed*(alpha_face*tmp39*(gamma_faceDD02*tmp73 + gamma_faceDD12*tmp64 + gamma_faceDD22*tmp74 + tmp2*tmp72) - tmp40*(gamma_faceDD02*tmp70 + gamma_faceDD12*tmp32 + gamma_faceDD22*tmp71 + tmp2*tmp69)) + tmp41*(gamma_faceDD02*tmp36 + gamma_faceDD12*tmp29 + gamma_faceDD22*tmp38 + tmp2*tmp32) + tmp68*(gamma_faceDD02*tmp66 + gamma_faceDD12*tmp61 + gamma_faceDD22*tmp67 + tmp2*tmp64);
  cons->rho = -dissipation_speed*(-tmp78 + tmp80) + rhob_l*tmp41*u4lU2 + rhob_r*tmp68*u4rU2;
  cons->tau = cmax_weight*(-rhob_l*tmp40*u4lU2 + tmp32*tmp81) + cmin_weight*(-rhob_r*tmp40*u4rU2 + tmp64*tmp81) - dissipation_speed*(tmp39*tmp5*tmp72 - tmp69*tmp81 + tmp78 - tmp80);
  cons->entropy = S_l*tmp41*u4lU2 + S_r*tmp68*u4rU2 - dissipation_speed*(-S_l*tmp40*u4lU0 + S_r*alpha_face*tmp39*u4rU0);
  return ghl_success;
}

void ghl_calculate_HLLE_fluxes_dirn1_hybrid_entropy(ghl_primitive_quantities *restrict prims_r, ghl_primitive_quantities *restrict prims_l, const ghl_eos_parameters *restrict eos, const ghl_metric_quantities *restrict metric_face, const double cmin_dirn1, const double cmax_dirn1, ghl_conservative_quantities *restrict cons) {
  ghl_abort_if_error(ghl_calculate_HLLE_fluxes_dirn1_hybrid_entropy_checked(prims_r, prims_l, eos, metric_face, cmin_dirn1, cmax_dirn1, cons));
}
