#include "ghl_radiation.h"
#include "ghl_nrpyeos_tabulated.h"
#include "NRPyLeakage_nucleon_blocking.h"
#include "NRPyLeakage_rate_helpers.h"

static double EnsureFinite(const double x) {
  if(robust_isfinite(x))
    return x;
  else
    return nrpyl_cgs_numerical_floor;
}

/*
 * (c) Leo Werneck
 * Compute GRMHD source terms following Ruffert et al. (1996)
 * https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
 */
ghl_error_codes_t NRPyLeakage_compute_neutrino_opacities_and_GRMHD_source_terms(
      const ghl_eos_parameters *restrict eos,
      const double rho,
      const double Y_e,
      const double T,
      const ghl_neutrino_optical_depths *restrict tau,
      ghl_neutrino_opacities *restrict kappa,
      double *restrict R_source,
      double *restrict Q_source) {

#ifdef GHL_DISABLE_HDF5
  return ghl_error_used_disabled_hdf5;
#endif

  // Step 1: Get chemical potentials and mass
  //         fractions using the EOS
  double muhat, mu_e, mu_p, mu_n, X_n, X_p;
  ghl_error_codes_t error = ghl_tabulated_compute_muhat_mue_mup_mun_Xn_Xp_from_T(eos, rho, Y_e, T, &muhat, &mu_e, &mu_p, &mu_n, &X_n, &X_p);
  if(error != ghl_success) {
    return error;
  }

  // Step 2: Compute rho in cgs units
  const double rho_cgs = rho * NRPyLeakage_units_geom_to_cgs_D;

  // Step 3: Derive free-nucleon scattering and transition populations from
  // the EOS mass fractions, retaining the kinetic degeneracy difference for
  // the reaction-energy shift.
  double B_n, B_p, Y_np, Y_pn, eta_n_minus_eta_p;
  error = NRPyLeakage_compute_nucleon_blocking(
      rho_cgs, T, X_n, X_p, &B_n, &B_p, &Y_np, &Y_pn,
      &eta_n_minus_eta_p);
  if(error != ghl_success)
    return error;

  // The blocking evaluator accepts only its derived interpolation-roundoff
  // envelope. Use the corresponding physical endpoints everywhere below.
  X_n = fmin(1.0, fmax(0.0, X_n));
  X_p = fmin(1.0, fmax(0.0, X_p));

  // Step 4: Compute the source terms
  //         Note: The code below is generated by NRPy+
  const double tmp_0 = (1.0/(T));
  const double tmp_1 = mu_e*tmp_0;
  double tmp_2_fd, tmp_16_fd, tmp_18_fd, tmp_19_fd;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_2_fd, 4, tmp_1);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_16_fd, 3, tmp_1);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_18_fd, 4, -tmp_1);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_19_fd, 3, -tmp_1);
  const double tmp_2 = tmp_2_fd;
  const double tmp_4 = exp(-tau->nue[0]);
  const double tmp_6 = NRPyLeakage_eta_nue_0*tmp_4 + (1 - tmp_4)*(-muhat*tmp_0 + tmp_1);
  const double tmp_7 = ((NRPyLeakage_alpha)*(NRPyLeakage_alpha));
  const double tmp_8 = M_PI/NRPyLeakage_hc3;
  const double tmp_10 = 8*NRPyLeakage_N_A*NRPyLeakage_beta*((T)*(T)*(T)*(T)*(T))*rho_cgs*tmp_8*((3.0/8.0)*tmp_7 + 1.0/8.0);
  const double tmp_12 = NRPyLeakage_enable_brems_nui_anui
                        * EnsureFinite(nrpyl_bremsstrahlung_number_rate(
                              T, rho_cgs, X_n, X_p));
  const double tmp_13 = exp(-tau->anue[0]);
  const double tmp_15 = NRPyLeakage_eta_anue_0*tmp_13 + (1 - tmp_13)*(muhat*tmp_0 - tmp_1);
  nrpyl_beta_moments beta_nue_emission = {0.0, 0.0};
  nrpyl_beta_moments beta_anue_emission = {0.0, 0.0};
  nrpyl_beta_moments beta_nue_absorption = {0.0, 0.0};
  nrpyl_beta_moments beta_anue_absorption = {0.0, 0.0};
  if(X_n > 0.0 && X_p > 0.0) {
    const double reaction_shift = nrpyl_compute_reaction_shift(
        T, muhat, eta_n_minus_eta_p);
    error = nrpyl_compute_beta_emission_moments(
        T, mu_e, tmp_6, 1, reaction_shift, &beta_nue_emission);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_emission_moments(
        T, mu_e, tmp_15, -1, reaction_shift, &beta_anue_emission);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_absorption_moments(
        T, mu_e, tmp_6, 1, reaction_shift, &beta_nue_absorption);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_absorption_moments(
        T, mu_e, tmp_15, -1, reaction_shift, &beta_anue_absorption);
    if(error != ghl_success)
      return error;
  }
  const double tmp_11 = NRPyLeakage_enable_beta_nue*
                        EnsureFinite(Y_pn*tmp_10*beta_nue_emission.number);
  const double tmp_16 = tmp_16_fd;
  const double tmp_17 = (1.0/(tmp_16));
  const double tmp_18 = tmp_18_fd;
  const double tmp_19 = tmp_19_fd;
  const double tmp_20 = (1.0/(tmp_19));
  const double tmp_21 = -1.0/2.0*tmp_17*tmp_2 - 1.0/2.0*tmp_18*tmp_20;
  const double tmp_22 = ((M_PI)*(M_PI));
  const double tmp_24 = (1.0/((NRPyLeakage_hc3)*(NRPyLeakage_hc3)));
  const double tmp_25 = tmp_16*tmp_22*tmp_24;
  const double tmp_26 = pow(T, 8);
  const double tmp_28 = (16.0/9.0)*NRPyLeakage_beta*tmp_19*tmp_25*tmp_26;
  const double tmp_29 = NRPyLeakage_enable_pair_nue_anue*EnsureFinite(NRPyLeakage_C1pC2_nue_anue*tmp_28/((exp(tmp_15 + tmp_21) + 1)*(exp(tmp_21 + tmp_6) + 1)));
  const double tmp_31 = (1.0/3.0)*tmp_22 + ((mu_e)*(mu_e))/((T)*(T));
  const double tmp_32 = NRPyLeakage_gamma_0*sqrt(tmp_31);
  const double tmp_34 = ((NRPyLeakage_gamma_0)*(NRPyLeakage_gamma_0))*tmp_31/(tmp_32 + 1);
  const double tmp_35 = -1.0/2.0*tmp_34 - 1;
  const double tmp_36 = (1.0/3.0)*((M_PI)*(M_PI)*(M_PI))*NRPyLeakage_beta*pow(NRPyLeakage_gamma_0, 6)*tmp_24*tmp_26*((tmp_31)*(tmp_31)*(tmp_31))*(tmp_32 + 1)*exp(-tmp_32)/NRPyLeakage_alpha_fs;
  const double tmp_37 = NRPyLeakage_enable_plasmon_nue_anue*EnsureFinite(((NRPyLeakage_C_V)*(NRPyLeakage_C_V))*tmp_36/((exp(tmp_15 + tmp_35) + 1)*(exp(tmp_35 + tmp_6) + 1)));
  const double tmp_38 = tmp_12 + tmp_29 + tmp_37;
  const double tmp_41 = B_n*((5.0/24.0)*tmp_7 + 1.0/24.0);
  const double tmp_42 = NRPyLeakage_N_A*NRPyLeakage_sigma_0*((T)*(T))*rho_cgs/((NRPyLeakage_m_e_c2)*(NRPyLeakage_m_e_c2));
  double tmp_43_fd, tmp_44_fd, tmp_51_fd, tmp_60_fd, tmp_61_fd, tmp_63_fd, tmp_70_fd, tmp_71_fd, tmp_78_fd, tmp_83_fd, tmp_87_fd4, tmp_87_fd2;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_43_fd, 2, tmp_6);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_44_fd, 4, tmp_6);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_51_fd, 5, tmp_6);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_60_fd, 2, tmp_15);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_61_fd, 4, tmp_15);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_63_fd, 5, tmp_15);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_70_fd, 3, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_71_fd, 5, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_78_fd, 3, tmp_6);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_83_fd, 3, tmp_15);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_87_fd4, 4, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_87_fd2, 2, 0);
  const double tmp_43 = tmp_43_fd;
  const double tmp_44 = tmp_44_fd;
  const double tmp_45 = tmp_44/tmp_43;
  const double tmp_47 = ((NRPyLeakage_C_V - 1)*(NRPyLeakage_C_V - 1));
  const double tmp_48 = B_p*((1.0/6.0)*tmp_47 + (5.0/24.0)*tmp_7);
  const double tmp_49 = tmp_42*tmp_48;
  const double tmp_50 = (3.0/4.0)*tmp_7 + 1.0/4.0;
  const double tmp_51 = tmp_51_fd;
  const double tmp_53 = EnsureFinite(tmp_45*tmp_49)
                      + EnsureFinite(tmp_41*tmp_42*tmp_45)
                      + EnsureFinite(tmp_42*Y_np*tmp_50*
                                     beta_nue_absorption.number);
  const double tmp_55 = 4*((T)*(T)*(T))*tmp_8;
  const double tmp_58 = NRPyLeakage_enable_beta_anue*
                        EnsureFinite(Y_np*tmp_10*beta_anue_emission.number);
  const double tmp_60 = tmp_60_fd;
  const double tmp_61 = tmp_61_fd;
  const double tmp_62 = tmp_42*tmp_61/tmp_60;
  const double tmp_63 = tmp_63_fd;
  const double tmp_65 = EnsureFinite(tmp_41*tmp_62)
                      + EnsureFinite(tmp_48*tmp_62)
                      + EnsureFinite(tmp_42*Y_pn*tmp_50*
                                     beta_anue_absorption.number);
  const double tmp_66 = EnsureFinite(nrpyl_bremsstrahlung_energy_rate(T, tmp_12));
  const double tmp_67 = 32*pow(T, 9);
  const double tmp_68 = (1.0/64.0)*((NRPyLeakage_hc3)*(NRPyLeakage_hc3))*tmp_17*tmp_20*(tmp_18*tmp_25*tmp_67 + tmp_19*tmp_2*tmp_22*tmp_24*tmp_67)/(tmp_22*tmp_26);
  const double tmp_69 = (1.0/2.0)*T*(tmp_34 + 2);
  const double tmp_70 = tmp_70_fd;
  const double tmp_71 = tmp_71_fd/tmp_70;
  const double tmp_73 = EnsureFinite(tmp_49*tmp_71) + EnsureFinite(tmp_41*tmp_42*tmp_71);
  const double tmp_74 = 4*((T)*(T)*(T)*(T))*tmp_8;
  const double tmp_75 = tmp_66 + EnsureFinite(tmp_29*tmp_68) + EnsureFinite(tmp_37*tmp_69);
  const double tmp_76 = tmp_75 + NRPyLeakage_enable_beta_nue*
      EnsureFinite(T*Y_pn*tmp_10*beta_nue_emission.energy);
  const double tmp_78 = tmp_78_fd;
  const double tmp_79 = tmp_51/tmp_78;
  const double tmp_81 = EnsureFinite(tmp_49*tmp_79)
                      + EnsureFinite(tmp_41*tmp_42*tmp_79)
                      + EnsureFinite(tmp_42*Y_np*tmp_50*
                                     beta_nue_absorption.energy);
  const double tmp_82 = tmp_75 + NRPyLeakage_enable_beta_anue*
      EnsureFinite(T*Y_np*tmp_10*beta_anue_emission.energy);
  const double tmp_83 = tmp_83_fd;
  const double tmp_84 = tmp_63/tmp_83;
  const double tmp_86 = EnsureFinite(tmp_49*tmp_84)
                      + EnsureFinite(tmp_41*tmp_42*tmp_84)
                      + EnsureFinite(tmp_42*Y_pn*tmp_50*
                                     beta_anue_absorption.energy);
  const double tmp_87 = tmp_87_fd4/tmp_87_fd2;
  // Free energy emission rate of a single heavy-lepton species. It is both the
  // numerator and the free-emission timescale of the tau->nux[1] suppression.
  const double Q_free_nux = tmp_66 + EnsureFinite(NRPyLeakage_enable_pair_nux_anux*tmp_68*EnsureFinite(NRPyLeakage_C1pC2_nux_anux*tmp_28/((exp(tmp_21) + 1)*(exp(tmp_21) + 1)))) + EnsureFinite(NRPyLeakage_enable_plasmon_nux_anux*tmp_69*EnsureFinite(tmp_36*tmp_47/((exp(tmp_35) + 1)*(exp(tmp_35) + 1))));
  const double R_free_nue = tmp_11 + tmp_38;
  const double R_free_anue = tmp_38 + tmp_58;
  const double R_eff_nue = nrpyl_effective_emission_rate(
      R_free_nue, tau->nue[0], tmp_53, tmp_43*tmp_55);
  const double R_eff_anue = nrpyl_effective_emission_rate(
      R_free_anue, tau->anue[0], tmp_65, tmp_55*tmp_60);
  const double Q_eff_nue = nrpyl_effective_emission_rate(
      tmp_76, tau->nue[1], tmp_81, tmp_74*tmp_78);
  const double Q_eff_anue = nrpyl_effective_emission_rate(
      tmp_82, tau->anue[1], tmp_86, tmp_74*tmp_83);
  const double Q_eff_nux = nrpyl_effective_emission_rate(
      Q_free_nux, tau->nux[1], tmp_73, tmp_70*tmp_74);
  *R_source = NRPyLeakage_amu*NRPyLeakage_units_cgs_to_geom_R*
              (-R_eff_nue + R_eff_anue);
  *Q_source = nrpyl_matter_energy_source(Q_eff_nue, Q_eff_anue, Q_eff_nux);
  kappa->nue[0] = NRPyLeakage_units_geom_to_cgs_L*tmp_53;
  kappa->nue[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_81;
  kappa->anue[0] = NRPyLeakage_units_geom_to_cgs_L*tmp_65;
  kappa->anue[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_86;
  kappa->nux[0] = NRPyLeakage_units_geom_to_cgs_L*
                  (EnsureFinite(tmp_49*tmp_87)
                   + EnsureFinite(tmp_41*tmp_42*tmp_87));
  kappa->nux[1] = NRPyLeakage_units_geom_to_cgs_L*tmp_73;
  const bool replaced_sources = nrpyl_sanitize_sources(R_source, Q_source);
  const bool replaced_opacities = nrpyl_sanitize_opacities(kappa);
  return replaced_sources || replaced_opacities
         ? ghl_error_nrpyleakage_nonfinite_output : ghl_success;
}
