#include "ghl_radiation.h"
#include "ghl_nrpyeos_tabulated.h"
#include "NRPyLeakage_nucleon_blocking.h"
#include "NRPyLeakage_rate_helpers.h"

static double EnsureFinite(const double x) {
  if(robust_isfinite(x))
    return x;
  else
    return nrpyl_cgs_numerical_floor;
}

/*
 * (c) Leo Werneck
 * Compute GRMHD source terms following Ruffert et al. (1996)
 * https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
 */
ghl_error_codes_t NRPyLeakage_compute_neutrino_opacities(
      const ghl_eos_parameters *restrict eos,
      const double rho,
      const double Y_e,
      const double T,
      const ghl_neutrino_optical_depths *restrict tau,
      ghl_neutrino_opacities *restrict kappa) {

#ifdef GHL_DISABLE_HDF5
  return ghl_error_used_disabled_hdf5;
#endif

  // Step 1: Get chemical potentials and mass
  //         fractions using the EOS
  double muhat, mu_e, mu_p, mu_n, X_n, X_p;
  ghl_error_codes_t error = ghl_tabulated_compute_muhat_mue_mup_mun_Xn_Xp_from_T(eos, rho, Y_e, T, &muhat, &mu_e, &mu_p, &mu_n, &X_n, &X_p);
  if(error != ghl_success) {
    return error;
  }

  // Step 2: Compute rho in cgs units
  const double rho_cgs = rho * NRPyLeakage_units_geom_to_cgs_D;

  // Step 3: Derive free-nucleon scattering and transition populations from
  // the EOS mass fractions, retaining the kinetic degeneracy difference for
  // the reaction-energy shift.
  double B_n, B_p, Y_np, Y_pn, eta_n_minus_eta_p;
  error = NRPyLeakage_compute_nucleon_blocking(
      rho_cgs, T, X_n, X_p, &B_n, &B_p, &Y_np, &Y_pn,
      &eta_n_minus_eta_p);
  if(error != ghl_success)
    return error;

  // The blocking evaluator accepts only its derived interpolation-roundoff
  // envelope. Use the corresponding physical endpoints everywhere below.
  X_n = fmin(1.0, fmax(0.0, X_n));
  X_p = fmin(1.0, fmax(0.0, X_p));

  // Step 4: Compute the source terms
  //         Note: The code below is generated by NRPy+
  const double tmp_0 = exp(-tau->nue[0]);
  const double tmp_1 = (1.0/(T));
  const double tmp_2 = mu_e*tmp_1;
  const double tmp_4 = NRPyLeakage_eta_nue_0*tmp_0 + (1 - tmp_0)*(-muhat*tmp_1 + tmp_2);
  double tmp_5_fd, tmp_7_fd, tmp_12_fd, tmp_15_fd;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_5_fd, 4, tmp_4);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_7_fd, 2, tmp_4);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_12_fd, 5, tmp_4);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_15_fd, 3, tmp_4);
  const double tmp_5 = tmp_5_fd;
  const double tmp_6 = NRPyLeakage_N_A*NRPyLeakage_sigma_0*((T)*(T))*rho_cgs/((NRPyLeakage_m_e_c2)*(NRPyLeakage_m_e_c2));
  const double tmp_7 = tmp_5*tmp_6/tmp_7_fd;
  const double tmp_9 = (5.0/24.0)*((NRPyLeakage_alpha)*(NRPyLeakage_alpha));
  const double tmp_10 = B_n*(tmp_9 + 1.0/24.0);
  const double tmp_11 = B_p*(tmp_9 + (1.0/6.0)*((NRPyLeakage_C_V - 1)*(NRPyLeakage_C_V - 1)));
  const double tmp_12 = tmp_12_fd;
  const double tmp_13 = (3.0/4.0)*((NRPyLeakage_alpha)*(NRPyLeakage_alpha)) + 1.0/4.0;
  const double tmp_15 = tmp_12/tmp_15_fd;
  const double tmp_17 = tmp_11*tmp_6;
  const double tmp_18 = exp(-tau->anue[0]);
  const double tmp_20 = NRPyLeakage_eta_anue_0*tmp_18 + (1 - tmp_18)*(muhat*tmp_1 - tmp_2);
  nrpyl_beta_moments beta_nue_absorption = {0.0, 0.0};
  nrpyl_beta_moments beta_anue_absorption = {0.0, 0.0};
  // At an exact single-species endpoint these moments take their analytic
  // zero-product limit; do not form the divergent reaction shift.
  if(X_n > 0.0 && X_p > 0.0) {
    const double reaction_shift = nrpyl_compute_reaction_shift(
        T, muhat, eta_n_minus_eta_p);
    error = nrpyl_compute_beta_absorption_moments(
        T, mu_e, tmp_4, 1, reaction_shift, &beta_nue_absorption);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_absorption_moments(
        T, mu_e, tmp_20, -1, reaction_shift, &beta_anue_absorption);
    if(error != ghl_success)
      return error;
  }
  double tmp_21_fd, tmp_22_fd, tmp_24_fd, tmp_26_fd, tmp_28_fd4, tmp_28_fd2, tmp_30_fd5, tmp_30_fd3;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_21_fd, 4, tmp_20);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_22_fd, 2, tmp_20);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_24_fd, 5, tmp_20);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_26_fd, 3, tmp_20);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_28_fd4, 4, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_28_fd2, 2, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_30_fd5, 5, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_30_fd3, 3, 0);
  const double tmp_21 = tmp_21_fd;
  const double tmp_22 = tmp_21/tmp_22_fd;
  const double tmp_24 = tmp_24_fd;
  const double tmp_26 = tmp_24/tmp_26_fd;
  const double tmp_28 = tmp_28_fd4/tmp_28_fd2;
  const double tmp_30 = tmp_30_fd5/tmp_30_fd3;
  kappa->nue[0] = NRPyLeakage_units_geom_to_cgs_L*
      (EnsureFinite(tmp_10*tmp_7) + EnsureFinite(tmp_11*tmp_7)
       + EnsureFinite(tmp_6*Y_np*tmp_13*beta_nue_absorption.number));
  kappa->nue[1] = NRPyLeakage_units_geom_to_cgs_L*
      (EnsureFinite(tmp_15*tmp_17) + EnsureFinite(tmp_10*tmp_15*tmp_6)
       + EnsureFinite(tmp_6*Y_np*tmp_13*beta_nue_absorption.energy));
  kappa->anue[0] = NRPyLeakage_units_geom_to_cgs_L*
      (EnsureFinite(tmp_17*tmp_22) + EnsureFinite(tmp_10*tmp_22*tmp_6)
       + EnsureFinite(tmp_6*Y_pn*tmp_13*beta_anue_absorption.number));
  kappa->anue[1] = NRPyLeakage_units_geom_to_cgs_L*
      (EnsureFinite(tmp_17*tmp_26) + EnsureFinite(tmp_10*tmp_26*tmp_6)
       + EnsureFinite(tmp_6*Y_pn*tmp_13*beta_anue_absorption.energy));
  kappa->nux[0] = NRPyLeakage_units_geom_to_cgs_L*(EnsureFinite(tmp_17*tmp_28) + EnsureFinite(tmp_10*tmp_28*tmp_6));
  kappa->nux[1] = NRPyLeakage_units_geom_to_cgs_L*(EnsureFinite(tmp_17*tmp_30) + EnsureFinite(tmp_10*tmp_30*tmp_6));

  // Step 5: Make sure public results are finite; otherwise use the established floor.
  return nrpyl_sanitize_opacities(kappa)
         ? ghl_error_nrpyleakage_nonfinite_output : ghl_success;
}
