#include "ghl_radiation.h"
#include "ghl_nrpyeos_tabulated.h"
#include "NRPyLeakage_nucleon_blocking.h"
#include "NRPyLeakage_rate_helpers.h"

static double EnsureFinite(const double x) {
  if(robust_isfinite(x))
    return x;
  else
    return nrpyl_cgs_numerical_floor;
}

/*
 * (c) Leo Werneck
 * Compute neutrino luminosities following Siegel & Metzger (2018)
 * https://arxiv.org/pdf/1711.00868.pdf
 * Neutrino rates: https://adsabs.harvard.edu/pdf/1996A%26A...311..532R
 */
ghl_error_codes_t NRPyLeakage_compute_neutrino_luminosities(
      const ghl_eos_parameters *restrict eos,
      const double alpha,
      const double gammaxx,
      const double gammaxy,
      const double gammaxz,
      const double gammayy,
      const double gammayz,
      const double gammazz,
      const double rho,
      const double Y_e,
      const double T,
      const double W,
      const ghl_neutrino_optical_depths *restrict tau,
      ghl_neutrino_luminosities *restrict lum) {

#ifdef GHL_DISABLE_HDF5
  return ghl_error_used_disabled_hdf5;
#endif

  // Step 1: Get chemical potentials and mass
  //         fractions using the EOS
  double muhat, mu_e, mu_p, mu_n, X_n, X_p;
  ghl_error_codes_t error = ghl_tabulated_compute_muhat_mue_mup_mun_Xn_Xp_from_T(eos, rho, Y_e, T, &muhat, &mu_e, &mu_p, &mu_n, &X_n, &X_p);
  if(error != ghl_success) {
    return error;
  }

  // Step 2: Compute rho in cgs units
  const double rho_cgs = rho * NRPyLeakage_units_geom_to_cgs_D;

  // Step 3: Derive free-nucleon scattering and transition populations from
  // the EOS mass fractions, retaining the kinetic degeneracy difference for
  // the reaction-energy shift.
  double B_n, B_p, Y_np, Y_pn, eta_n_minus_eta_p;
  error = NRPyLeakage_compute_nucleon_blocking(
      rho_cgs, T, X_n, X_p, &B_n, &B_p, &Y_np, &Y_pn,
      &eta_n_minus_eta_p);
  if(error != ghl_success)
    return error;

  // The blocking evaluator accepts only its derived interpolation-roundoff
  // envelope. Use the corresponding physical endpoints everywhere below.
  X_n = fmin(1.0, fmax(0.0, X_n));
  X_p = fmin(1.0, fmax(0.0, X_p));

  // Step 4: Compute the source terms
  //         Note: The code below is generated by NRPy+
  const double tmp_0 = (1.0/(T));
  const double tmp_1 = mu_e*tmp_0;
  double tmp_2_fd;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_2_fd, 4, tmp_1);
  const double tmp_2 = tmp_2_fd;
  const double tmp_4 = exp(-tau->nue[0]);
  const double tmp_6 = NRPyLeakage_eta_nue_0*tmp_4 + (1 - tmp_4)*(-muhat*tmp_0 + tmp_1);
  const double tmp_7 = ((NRPyLeakage_alpha)*(NRPyLeakage_alpha));
  const double tmp_8 = M_PI/NRPyLeakage_hc3;
  const double tmp_10 = 8*NRPyLeakage_N_A*NRPyLeakage_beta*((T)*(T)*(T)*(T)*(T))*rho_cgs*tmp_8*((3.0/8.0)*tmp_7 + 1.0/8.0);
  const double tmp_11 = EnsureFinite(nrpyl_bremsstrahlung_energy_rate(
      T, NRPyLeakage_enable_brems_nui_anui
               * EnsureFinite(nrpyl_bremsstrahlung_number_rate(T, rho_cgs, X_n, X_p))));
  const double tmp_12 = exp(-tau->anue[0]);
  const double tmp_14 = NRPyLeakage_eta_anue_0*tmp_12 + (1 - tmp_12)*(muhat*tmp_0 - tmp_1);
  nrpyl_beta_moments beta_nue_emission = {0.0, 0.0};
  nrpyl_beta_moments beta_anue_emission = {0.0, 0.0};
  nrpyl_beta_moments beta_nue_absorption = {0.0, 0.0};
  nrpyl_beta_moments beta_anue_absorption = {0.0, 0.0};
  if(X_n > 0.0 && X_p > 0.0) {
    const double reaction_shift = nrpyl_compute_reaction_shift(
        T, muhat, eta_n_minus_eta_p);
    error = nrpyl_compute_beta_emission_moments(
        T, mu_e, tmp_6, 1, reaction_shift, &beta_nue_emission);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_emission_moments(
        T, mu_e, tmp_14, -1, reaction_shift, &beta_anue_emission);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_absorption_moments(
        T, mu_e, tmp_6, 1, reaction_shift, &beta_nue_absorption);
    if(error != ghl_success)
      return error;
    error = nrpyl_compute_beta_absorption_moments(
        T, mu_e, tmp_14, -1, reaction_shift, &beta_anue_absorption);
    if(error != ghl_success)
      return error;
  }
  const double tmp_15 = ((M_PI)*(M_PI));
  const double tmp_17 = (1.0/3.0)*tmp_15 + ((mu_e)*(mu_e))/((T)*(T));
  const double tmp_18 = NRPyLeakage_gamma_0*sqrt(tmp_17);
  const double tmp_20 = ((NRPyLeakage_gamma_0)*(NRPyLeakage_gamma_0))*tmp_17/(tmp_18 + 1);
  const double tmp_21 = -1.0/2.0*tmp_20 - 1;
  const double tmp_23 = (1.0/((NRPyLeakage_hc3)*(NRPyLeakage_hc3)));
  const double tmp_24 = pow(T, 8);
  const double tmp_26 = (1.0/3.0)*((M_PI)*(M_PI)*(M_PI))*NRPyLeakage_beta*pow(NRPyLeakage_gamma_0, 6)*((tmp_17)*(tmp_17)*(tmp_17))*tmp_23*tmp_24*(tmp_18 + 1)*exp(-tmp_18)/NRPyLeakage_alpha_fs;
  const double tmp_27 = (1.0/2.0)*T*(tmp_20 + 2);
  double tmp_28_fd, tmp_30_fd, tmp_31_fd;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_28_fd, 3, tmp_1);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_30_fd, 4, -tmp_1);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_31_fd, 3, -tmp_1);
  const double tmp_28 = tmp_28_fd;
  const double tmp_29 = (1.0/(tmp_28));
  const double tmp_30 = tmp_30_fd;
  const double tmp_31 = tmp_31_fd;
  const double tmp_32 = (1.0/(tmp_31));
  const double tmp_33 = -1.0/2.0*tmp_2*tmp_29 - 1.0/2.0*tmp_30*tmp_32;
  const double tmp_34 = tmp_15*tmp_23*tmp_28;
  const double tmp_35 = (16.0/9.0)*NRPyLeakage_beta*tmp_24*tmp_31*tmp_34;
  const double tmp_36 = 32*pow(T, 9);
  const double tmp_37 = (1.0/64.0)*((NRPyLeakage_hc3)*(NRPyLeakage_hc3))*tmp_29*tmp_32*(tmp_15*tmp_2*tmp_23*tmp_31*tmp_36 + tmp_30*tmp_34*tmp_36)/(tmp_15*tmp_24);
  const double tmp_38 = tmp_11 + EnsureFinite(NRPyLeakage_enable_pair_nue_anue*tmp_37*EnsureFinite(NRPyLeakage_C1pC2_nue_anue*tmp_35/((exp(tmp_14 + tmp_33) + 1)*(exp(tmp_33 + tmp_6) + 1)))) + EnsureFinite(NRPyLeakage_enable_plasmon_nue_anue*tmp_27*EnsureFinite(((NRPyLeakage_C_V)*(NRPyLeakage_C_V))*tmp_26/((exp(tmp_14 + tmp_21) + 1)*(exp(tmp_21 + tmp_6) + 1))));
  const double tmp_39 = tmp_38 + NRPyLeakage_enable_beta_nue*
      EnsureFinite(T*Y_pn*tmp_10*beta_nue_emission.energy);
  double tmp_40_fd, tmp_41_fd;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_40_fd, 5, tmp_6);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_41_fd, 3, tmp_6);
  const double tmp_40 = tmp_40_fd;
  const double tmp_41 = tmp_41_fd;
  const double tmp_42 = NRPyLeakage_N_A*NRPyLeakage_sigma_0*((T)*(T))*rho_cgs/((NRPyLeakage_m_e_c2)*(NRPyLeakage_m_e_c2));
  const double tmp_43 = tmp_40*tmp_42/tmp_41;
  const double tmp_45 = B_n*((5.0/24.0)*tmp_7 + 1.0/24.0);
  const double tmp_46 = ((NRPyLeakage_C_V - 1)*(NRPyLeakage_C_V - 1));
  const double tmp_47 = B_p*((1.0/6.0)*tmp_46 + (5.0/24.0)*tmp_7);
  const double tmp_48 = (3.0/4.0)*tmp_7 + 1.0/4.0;
  const double tmp_49 = 4*((T)*(T)*(T)*(T))*tmp_8;
  const double tmp_52 = NRPyLeakage_units_cgs_to_geom_Q*W*((alpha)*(alpha))*sqrt(gammaxx*gammayy*gammazz - gammaxx*((gammayz)*(gammayz)) - ((gammaxy)*(gammaxy))*gammazz + 2*gammaxy*gammaxz*gammayz - ((gammaxz)*(gammaxz))*gammayy);
  const double tmp_54 = tmp_38 + NRPyLeakage_enable_beta_anue*
      EnsureFinite(T*Y_np*tmp_10*beta_anue_emission.energy);
  double tmp_55_fd, tmp_56_fd, tmp_60_fd, tmp_61_fd;
  NRPYLEAKAGE_FD_OR_RETURN(tmp_55_fd, 5, tmp_14);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_56_fd, 3, tmp_14);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_60_fd, 3, 0);
  NRPYLEAKAGE_FD_OR_RETURN(tmp_61_fd, 5, 0);
  const double tmp_55 = tmp_55_fd;
  const double tmp_56 = tmp_56_fd;
  const double tmp_57 = tmp_55/tmp_56;
  const double tmp_60 = tmp_60_fd;
  const double tmp_61 = tmp_61_fd/tmp_60;
  // Free energy emission rate of a single heavy-lepton species. It is both the
  // numerator and the free-emission timescale of the tau->nux[1] suppression.
  const double Q_free_nux = tmp_11 + EnsureFinite(NRPyLeakage_enable_pair_nux_anux*tmp_37*EnsureFinite(NRPyLeakage_C1pC2_nux_anux*tmp_35/((exp(tmp_33) + 1)*(exp(tmp_33) + 1)))) + EnsureFinite(NRPyLeakage_enable_plasmon_nux_anux*tmp_27*EnsureFinite(tmp_26*tmp_46/((exp(tmp_21) + 1)*(exp(tmp_21) + 1))));
  const double kappa_nue = EnsureFinite(tmp_43*tmp_45)
                         + EnsureFinite(tmp_43*tmp_47)
                         + EnsureFinite(tmp_42*Y_np*tmp_48*
                                        beta_nue_absorption.energy);
  const double kappa_anue = EnsureFinite(tmp_42*tmp_45*tmp_57)
                          + EnsureFinite(tmp_42*tmp_47*tmp_57)
                          + EnsureFinite(tmp_42*Y_pn*tmp_48*
                                         beta_anue_absorption.energy);
  const double kappa_nux = EnsureFinite(tmp_42*tmp_45*tmp_61)
                         + EnsureFinite(tmp_42*tmp_47*tmp_61);
  const double Q_eff_nue = nrpyl_effective_emission_rate(
      tmp_39, tau->nue[1], kappa_nue, tmp_41*tmp_49);
  const double Q_eff_anue = nrpyl_effective_emission_rate(
      tmp_54, tau->anue[1], kappa_anue, tmp_49*tmp_56);
  const double Q_eff_nux = nrpyl_effective_emission_rate(
      Q_free_nux, tau->nux[1], kappa_nux, tmp_49*tmp_60);
  lum->nue = tmp_52*Q_eff_nue;
  lum->anue = tmp_52*Q_eff_anue;
  lum->nux = tmp_52*Q_eff_nux;
  return nrpyl_sanitize_luminosities(lum)
         ? ghl_error_nrpyleakage_nonfinite_output : ghl_success;
}
