name: Ubuntu-intel

on:
  push:
    paths-ignore: ['docs/**', '*.md', 'Makefile_old', '.gitattributes', '.gitignore', 'AUTHORS', 'LICENSE', 'implementations/**']
    branches: main
  pull_request:
    paths-ignore: ['docs/**', '*.md', 'Makefile_old', '.gitattributes', '.gitignore', 'AUTHORS', 'LICENSE', 'implementations/**']

jobs:
  flux:
    strategy:
      fail-fast: false
      matrix:
        test-function: [hybrid_flux, tabulated_flux]
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup OS and compiler
        uses: ./.github/actions/OS_setup
        with:
          compiler: 'intel'
      - name: Compile GRHayL
        uses: ./.github/actions/compile_GRHayL
        with:
          compiler: 'intel'
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/GRHayL/TestData/main/flux_source/${{ matrix.test-function }}_input.bin
          curl -O https://raw.githubusercontent.com/GRHayL/TestData/main/flux_source/${{ matrix.test-function }}_output.bin
          curl -O https://raw.githubusercontent.com/GRHayL/TestData/main/flux_source/${{ matrix.test-function }}_output_pert.bin
          curl -O https://stellarcollapse.org/EOS/SLy4_3335_rho391_temp163_ye66.h5.bz2 && bunzip2 SLy4_3335_rho391_temp163_ye66.h5.bz2
      - name: Run flux unit test for ${{ matrix.test-function }} function
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./test/unit_test_${{ matrix.test-function }}
      - name: Generate coverage report
        uses: ./.github/actions/code-coverage
        with:
          compiler: 'intel'
