name: Ubuntu-gcc

on:
  push:
    paths-ignore: 'docs/**'
    branches: main
  pull_request:

jobs:
  con-to-prim:
    strategy:
      fail-fast: false
      matrix:
        test-function: [apply_inequality_fixes, Noble2D_Hybrid_Multi_Method, font_fix, enforce_primitive_limits_and_output_u0, compute_conservs_and_Tmunu]
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: |
          # use apt-spy2 to select closest apt mirror,
          # which helps avoid connectivity issues in Azure;
          # see https://github.com/actions/virtual-environments/issues/675
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          # after selecting a specific mirror, we need to run 'apt-get update'
          sudo apt-get update
          sudo apt-get install -y gcc libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          export COMPILER=gnu
          make -j
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/Noble2D_initial_data.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/${{ matrix.test-function }}.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/${{ matrix.test-function }}_pert.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/md5/${{ matrix.test-function }}.md5
          md5sum -c ${{ matrix.test-function }}.md5
      - name: Run con2prim unit test for ${{ matrix.test-function }} function
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_${{ matrix.test-function }}

  reconstruction:
    strategy:
      fail-fast: false
      matrix:
        test-function: [simple_ppm]
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: |
          # use apt-spy2 to select closest apt mirror,
          # which helps avoid connectivity issues in Azure;
          # see https://github.com/actions/virtual-environments/issues/675
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          # after selecting a specific mirror, we need to run 'apt-get update'
          sudo apt-get update
          sudo apt-get install -y gcc libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          export COMPILER=gnu
          make -j
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/reconstruction/${{ matrix.test-function }}_initial_data.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/reconstruction/${{ matrix.test-function }}.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/reconstruction/${{ matrix.test-function }}_pert.bin
      - name: Run reconstruction unit test for ${{ matrix.test-function }} function
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_${{ matrix.test-function }}

  induction:
    strategy:
      fail-fast: false
      matrix:
        test-function: [HLL_flux, phitilde_and_A_gauge_rhs]
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: |
          # use apt-spy2 to select closest apt mirror,
          # which helps avoid connectivity issues in Azure;
          # see https://github.com/actions/virtual-environments/issues/675
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          # after selecting a specific mirror, we need to run 'apt-get update'
          sudo apt-get update
          sudo apt-get install -y gcc libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          export COMPILER=gnu
          make -j
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/induction/${{ matrix.test-function }}_initial_data.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/induction/${{ matrix.test-function }}.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/induction/${{ matrix.test-function }}_pert.bin
      - name: Run induction equation unit test for ${{ matrix.test-function }} function
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_${{ matrix.test-function }}

  tabulated-eos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: |
          # use apt-spy2 to select closest apt mirror,
          # which helps avoid connectivity issues in Azure;
          # see https://github.com/actions/virtual-environments/issues/675
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          # after selecting a specific mirror, we need to run 'apt-get update'
          sudo apt-get update
          sudo apt-get install -y gcc libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          export COMPILER=gnu
          make -j
      - name: Copy test data to working directory
        run: curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/EOS/simple_table.h5
      - name: Run tabulated EOS unit test
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_tabulated_eos simple_table.h5

  flux_source:
    strategy:
      fail-fast: false
      matrix:
        test-function: [flux_source]
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: |
          # use apt-spy2 to select closest apt mirror,
          # which helps avoid connectivity issues in Azure;
          # see https://github.com/actions/virtual-environments/issues/675
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          # after selecting a specific mirror, we need to run 'apt-get update'
          sudo apt-get update
          sudo apt-get install -y gcc libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          export COMPILER=gnu
          make -j
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/flux_source/${{ matrix.test-function }}_dirn1.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/flux_source/${{ matrix.test-function }}_dirn2.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/flux_source/${{ matrix.test-function }}_dirn3.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/flux_source/${{ matrix.test-function }}_output_rhs_data.bin
      - name: Run flux_source unit test for ${{ matrix.test-function }} functions
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_${{ matrix.test-function }}
