name: Ubuntu-clang

on:
  push:
    paths-ignore: ['docs/**', '*.md', 'Makefile_old', '.gitattributes', '.gitignore', 'AUTHORS', 'LICENSE', 'implementations/**']
    branches: main
  pull_request:

jobs:
  ET-Legacy:
    strategy:
      fail-fast: false
      matrix:
        test-function: [ET_Legacy_conservs, ET_Legacy_primitives, ET_Legacy_induction_gauge_rhs, ET_Legacy_HLL_flux, ET_Legacy_reconstruction, ET_Legacy_flux_source]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup OS and compiler
        uses: ./.github/actions/OS_setup
        with:
          OS: 'Ubuntu'
          compiler: 'clang'
      - name: Compile GRHayL
        uses: ./.github/actions/compile_GRHayL
        with:
          OS: 'Ubuntu'
          compiler: 'clang'
      - name: Copy test data to working directory
        run: |
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/ET_Legacy/${{ matrix.test-function }}_input.bin -o ${{ matrix.test-function }}_input.bin
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/ET_Legacy/${{ matrix.test-function }}_output.bin -o ${{ matrix.test-function }}_output.bin
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/ET_Legacy/${{ matrix.test-function }}_output_pert.bin -o ${{ matrix.test-function }}_output_pert.bin
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/ET_Legacy/md5/${{ matrix.test-function }}.md5 -o ${{ matrix.test-function }}.md5
           md5sum -c ${{ matrix.test-function }}.md5
      - name: Run ET IllinoisGRMHD unit test for ${{ matrix.test-function }}
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./test/unit_test_${{ matrix.test-function }}

  con-to-prim:
    strategy:
      fail-fast: false
      matrix:
        test-function: [apply_inequality_fixes, Noble2D_Hybrid_Multi_Method, font_fix, enforce_primitive_limits_and_compute_u0, compute_conservs_and_Tmunu]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup OS and compiler
        uses: ./.github/actions/OS_setup
        with:
          OS: 'Ubuntu'
          compiler: 'clang'
      - name: Compile GRHayL
        uses: ./.github/actions/compile_GRHayL
        with:
          OS: 'Ubuntu'
          compiler: 'clang'
      - name: Copy test data to working directory
        run: |
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/Noble2D_initial_data.bin -o Noble2D_initial_data.bin
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/${{ matrix.test-function }}.bin -o ${{ matrix.test-function }}.bin
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/${{ matrix.test-function }}_pert.bin -o ${{ matrix.test-function }}_pert.bin
          curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/md5/${{ matrix.test-function }}.md5 -o ${{ matrix.test-function }}.md5
           md5sum -c ${{ matrix.test-function }}.md5
      - name: Run con2prim unit test for ${{ matrix.test-function }} function
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./test/unit_test_${{ matrix.test-function }}

  tabulated-eos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup OS and compiler
        uses: ./.github/actions/OS_setup
        with:
          OS: 'Ubuntu'
          compiler: 'clang'
      - name: Compile GRHayL
        uses: ./.github/actions/compile_GRHayL
        with:
          OS: 'Ubuntu'
          compiler: 'clang'
      - name: Copy test data to working directory
        run: curl https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/EOS/simple_table.h5 -o simple_table.h5
      - name: Run tabulated EOS unit test
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./test/unit_test_tabulated_eos simple_table.h5
