name: Ubuntu-clang

on:
  push:
    branches: main
  pull_request:

jobs:
  con-to-prim:
    strategy:
      fail-fast: false
      matrix:
        test-function: [apply_inequality_fixes, font_fix, enforce_primitive_limits_and_output_u0]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: sudo apt-get update && sudo apt-get install -y clang-14 libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          sed -i 's/COMPILER = "gnu"/COMPILER = "clang"/' Makefile
          sed -i 's/= clang/= clang-14/' Makefile
          make
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/C2P_Noble2D_initial_data.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/C2P_${{ matrix.test-function }}.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/con2prim/C2P_${{ matrix.test-function }}_pert.bin
      - name: Run con2prim unit test for ${{ matrix.test-function }} function
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_${{ matrix.test-function }}

  induction-gauge-rhs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: sudo apt-get update && sudo apt-get install -y clang-14 libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          sed -i 's/COMPILER = "gnu"/COMPILER = "clang"/' Makefile
          sed -i 's/= clang/= clang-14/' Makefile
          make
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/induction/gauge_rhs_initial_data.bin
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/induction/phitilde_and_A_gauge_rhs.bin
      - name: Run induction equation gauge RHS unit test
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_gauge_rhs


  tabulated-eos:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Install needed ubuntu packages
        run: sudo apt-get update && sudo apt-get install -y clang-14 libhdf5-serial-dev
      - name: Compile GRHayL
        run: |
          sed -i 's/COMPILER = "gnu"/COMPILER = "clang"/' Makefile
          sed -i 's/= clang/= clang-14/' Makefile
          make
      - name: Copy test data to working directory
        run: |
          curl -O https://raw.githubusercontent.com/SamuelCupp/GRHayL_TestData/main/EOS/simple_table.h5
      - name: Run tabulated EOS unit test
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib ./exe/unit_test_tabulated_eos simple_table.h5
